config/routes.rb
Rails.application.routes.draw do
  resources :planets

  root "pages#home"
  
  get "contact" => "pages#contact"
  get "mercury" => "pages#mercury"
  get "venus"   => "pages#venus"
  get "earth"   => "pages#earth"
  get "mars"    => "pages#mars"
  get "jupiter" => "pages#jupiter"
  get "saturn"  => "pages#saturn"
  get "uranus"  => "pages#uranus"
  get "neptune" => "pages#neptune"
  get "pluto"   => "pages#pluto"
  
  

end

app/models/planet.rb
class Planet < ActiveRecord::Base
    has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
   def home
   end
  
   def contact
   end

   def mercury
   end

   def venus
   end

   def earth
   end

   def mars
   end

   def jupiter
   end

   def saturn
   end

   def uranus
   end

   def neptune
   end

   def pluto
   end

end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  before_action :set_planet, only: [:show, :edit, :update, :destroy]

  # GET /planets
  # GET /planets.json
  def index
    @planets = Planet.all
  end

  # GET /planets/1
  # GET /planets/1.json
  def show
  end

  # GET /planets/new
  def new
    @planet = Planet.new
  end

  # GET /planets/1/edit
  def edit
  end

  # POST /planets
  # POST /planets.json
  def create
    @planet = Planet.new(planet_params)

    respond_to do |format|
      if @planet.save
        format.html { redirect_to @planet, notice: 'Planet was successfully created.' }
        format.json { render :show, status: :created, location: @planet }
      else
        format.html { render :new }
        format.json { render json: @planet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /planets/1
  # PATCH/PUT /planets/1.json
  def update
    respond_to do |format|
      if @planet.update(planet_params)
        format.html { redirect_to @planet, notice: 'Planet was successfully updated.' }
        format.json { render :show, status: :ok, location: @planet }
      else
        format.html { render :edit }
        format.json { render json: @planet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /planets/1
  # DELETE /planets/1.json
  def destroy
    @planet.destroy
    respond_to do |format|
      format.html { redirect_to planets_url, notice: 'Planet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_planet
      @planet = Planet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def planet_params
      params.require(:planet).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Planets of the Solar System</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Pick a Planet <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Mercury", mercury_path %></li>
            <li><%= link_to "Venus", venus_path %></li>
            <li><%= link_to "Earth", earth_path %></li>
            <li><%= link_to "Mars", mars_path %></li>
            <li><%= link_to "Jupiter", jupiter_path %></li>
            <li><%= link_to "Saturn", saturn_path %></li>
            <li><%= link_to "Uranus", uranus_path %></li>
            <li><%= link_to "Neptune", neptune_path %></li>
            <li><%= link_to "Pluto", pluto_path %></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
    
      </div><!-- /.navbar-collapse -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Contact", contact_path %></li> 
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Planets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container-fluid">
   <%= yield %>
  </div>

</body>
</html>

app/views/pages/contact.html.erb
<h1>Contact Us</h1>

app/views/pages/earth.html.erb
<h1>Earth</h1>

app/views/pages/home.html.erb
<div class="jumbotron">
<center><h1>The Planets of the Solar System</h1><center>
<p>Learn about all the planets including Pluto</p>
</div>
<div class="container"><
  <br><center><%=image_tag("planets.jpg", alt: "Solar System")%><center><br>
       <body>
      <p> The Solar System comprises of the Sun and the objets that orbit it, whether they orbit it directly 
      or by orbiting other objects that orbit it directly.  Of those objects that orbit the Sun directly, the 
      largets eight are the planets tha form the planetary system around it, while the remainder are significantly 
      smaller objects, such as dwarf planets and small Solar System bodies such as comets and asteroids.</br>

      <br>The Solar System formed 4.6 billion years ago from the gravitational collapse of a giant molecular cloud
      The vast majority of the system;s mass is in the Sun, with most of the remaining mass contained in Jupiter.
      The four smaller inner planets, Mercury, Venus, Earth and Mars also called the terrestrial planets, are 
      primarily composed of rock and metal.  The four outer planets, called the gas giants, are substantially more
      massive than the terrestrials.  The two largesy, Jupiter and Saturn, are composed mainly of hydrogen and helium;
      the two outersost planets, Uranus and Neptune, are composed largely of substances with relatively high melting 
      points (compared with the hydrogen and helium), called ices, such as water, ammonia, and methane, and are often 
      referred to separately as "ice giants".  all planets have almost circular orbits that lie withing a nearly flat 
      disc called the ecliptic plane.</br>

      <br>The Soalr System also contains regions populated by smaller objects.  the asteroid belt, which lies between Mars 
      and Jupiter, mostly contains objects composed, like the terrestial planets, of rock and metal.  Beyonf Neptune's
      orbit li the Kuiper belt and scattered disc, linked populationsof trans-Neptunian objects composed mostly of ices.
      Within these populations are several dozen to more than ten thousand objects that may be large enough to have been 
      rounded by their own gravity.  Such objects are referred to as dwarf plants.  Identified dwarf planets include the
      asteroid Ceres and the trans-Neptunian objects Plito and Eris.  In addition to these two regions, various other 
      small-body populations, including comets, centaurs and interplanetary dust, freely travel between regions. Six of 
      the planets, at least three of the dwarf plents, and many smaller bodies are orbitied b natural satelites, usually
      termed "moons" after Earth's Moon.  Each of the outer planet is encircled by planetary rings of dust and other 
      small objects.</br>

      <br> The soalr wind, a flow of plasma from the Sun, breates a bubble in the interstellar medium know as the heliosphere, 
      which extends out to the edge of the scattered disc.  The Oort cloud, which is believed to be the source for long-
      period comets, may also exist at a distance roughly a thousand times further than the heliosphere.  The heliopause
      is the point at which pressure from teh solar wind is equal to the opposinf pressure of interstellar wind.  The 
      Solar System is located in the Orion Arm, 26,000 light years away from the Milky Way.</br>

      for many thousands of years, humaity, with a few notable exceptions, did not recognize the existence of the Solar 
      System.  People believed Earth to be stationay at the center of the universe and categorically different from the 
      divine or ethereal objects that moved theough the sky.  Although Greek philosopher Aristarchus of Samos had 
      speculated on a helicentric reordering of the cosmos, Nicolaus Copernicus was the first to develop a mathematically
      predictice heliocentric system. In the 17th-century, Galileo Galilei, Johannes Kepler and Issac Newton, developed an
      understanding of physics that led to the gradual acceptance of the idea that Earth moves around the Sun and that the 
      planets are governed by the same physical laws that governed Earth.  The invention of the telescope led to the 
      discovery of furher planets and moons.  Improvements in the telescope and the use of unmanned spacecraft have enabled
      the investigation of geological phenomena, such as moutains, craters, seasonal meterological phenomena, such as clouds,
      dust storms and ice caps on the other planets.<p>
    </div>
    <body>

app/views/pages/jupitar.html.erb
<h1>Jupiter</h1>

app/views/pages/mars.html.erb
<h1>Mars</h1>

app/views/pages/mercury.html.erb
<h1>Mercury</h1>

app/views/pages/neptune.html.erb
<h1>Neptune</h1>

app/views/pages/pluto.html.erb
<h1>PLuto</h1>

app/views/pages/saturn.html.erb
<h1>Saturn</h1>

app/views/pages/uranus.html.erb
<h1>Saturn</h1>

app/views/pages/venus.html.erb
<h1>Venus</h1>

app/views/planets/_form.html.erb
<%= form_for(@planet) do |f| %>
  <% if @planet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@planet.errors.count, "error") %> prohibited this planet from being saved:</h2>

      <ul>
      <% @planet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/planets/edit.html.erb
<h1>Editing planet</h1>

<%= render 'form' %>

<%= link_to 'Show', @planet %> |
<%= link_to 'Back', planets_path %>

app/views/planets/index.html.erb
<h1>Listing planets</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @planets.each do |planet| %>
      <tr>
        <td><%= planet.description %></td>
        <td><%= link_to 'Show', planet %></td>
        <td><%= link_to 'Edit', edit_planet_path(planet) %></td>
        <td><%= link_to 'Destroy', planet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Planet', new_planet_path %>

app/views/planets/new.html.erb
<h1>New planet</h1>

<%= render 'form' %>

<%= link_to 'Back', planets_path %>

app/views/planets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @planet.description %>
</p>

<%= link_to 'Edit', edit_planet_path(@planet) %> |
<%= link_to 'Back', planets_path %>